[package]
name = "conflux-reputation"
description = "Contribution scoring and Byzantine detection for Conflux FL."
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
tracing.workspace = true

[dev-dependencies]
tracing-test.workspace = true
