//! Emit the aggregation catalog straight from the strategy registry.
//!
//! The count, the method list, the family each belongs to, and the paper
//! each cites are **not** hand-maintained here — they come from the same
//! `inventory::submit!` entries that make a method buildable at all
//! (`conflux_config::entries`). This is the answer to a drift that bit
//! the docs repeatedly: "twenty-one methods" vs "twenty-two", a row
//! missing after a method landed. A doc table regenerated from this can
//! only disagree with reality if the registry itself is wrong, and a
//! test already forbids that.
//!
//! ```bash
//! cargo run -p conflux-core --example catalog                # Markdown
//! cargo run -p conflux-core --example catalog -- --format json
//! ```
//!
//! The prose a human writes about *why* a method matters stays in the
//! docs; this owns the facts that can go stale on their own. One more
//! fact comes from the source tree rather than the registry: which
//! `baselines/*/baseline.toml` reproduce each method.

use std::collections::BTreeMap;

use conflux_config::{StrategyKind, entries};

fn main() {
    // Force `conflux-core`'s lib to link: `inventory::submit!` statics
    // are dead-stripped if nothing references the crate that holds them,
    // and this example otherwise touches only `conflux-config`. One real
    // reference keeps every aggregator registration in the binary.
    let _ = conflux_core::build_aggregator;

    let json = std::env::args().any(|a| a == "--format=json" || a == "json")
        || std::env::args()
            .collect::<Vec<_>>()
            .windows(2)
            .any(|w| w[0] == "--format" && w[1] == "json");

    // Registration order is not meaningful; group by family, then sort
    // names within each so the output is stable across builds.
    let mut by_family: BTreeMap<&str, Vec<&conflux_config::StrategyEntry>> = BTreeMap::new();
    for entry in entries(StrategyKind::Aggregator) {
        by_family.entry(entry.family).or_default().push(entry);
    }
    for v in by_family.values_mut() {
        v.sort_by_key(|e| e.name);
    }
    let total: usize = by_family.values().map(Vec::len).sum();

    // A deliberate family order: the shape of the catalog, not
    // alphabetical. Families the registry has but this list does not are
    // appended, so a new family cannot vanish from the output silently.
    let preferred = ["averaging", "robust", "temporal", "trusted", "optimization"];
    let mut order: Vec<&str> = preferred
        .iter()
        .copied()
        .filter(|f| by_family.contains_key(f))
        .collect();
    for f in by_family.keys() {
        if !order.contains(f) {
            order.push(f);
        }
    }

    let baselines = baselines_by_method();
    if json {
        print_json(&by_family, &order, total, &baselines);
    } else {
        print_markdown(&by_family, &order, total, &baselines);
    }
}

/// Which baselines reproduce each method: every `baselines/*/baseline.toml`
/// beside this crate, keyed by its `[method].aggregator`. Read from the
/// source tree, so a checkout without a `baselines/` directory simply
/// reports none rather than failing.
fn baselines_by_method() -> BTreeMap<String, Vec<String>> {
    let mut out: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../baselines");
    let Ok(read) = std::fs::read_dir(&dir) else {
        return out;
    };
    let mut names: Vec<String> = read
        .flatten()
        .filter(|e| e.path().is_dir())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| !n.starts_with('_'))
        .collect();
    names.sort();
    for name in names {
        let Ok(text) = std::fs::read_to_string(dir.join(&name).join("baseline.toml")) else {
            continue;
        };
        let Ok(manifest) = toml::from_str::<toml::Table>(&text) else {
            continue;
        };
        if let Some(method) = manifest
            .get("method")
            .and_then(|m| m.get("aggregator"))
            .and_then(|a| a.as_str())
        {
            out.entry(method.to_string()).or_default().push(name);
        }
    }
    out
}

fn print_markdown(
    by_family: &BTreeMap<&str, Vec<&conflux_config::StrategyEntry>>,
    order: &[&str],
    total: usize,
    baselines: &BTreeMap<String, Vec<String>>,
) {
    println!("<!-- Generated by `cargo run -p conflux-core --example catalog`.");
    println!("     Facts come from the strategy registry and baselines/*/baseline.toml;");
    println!("     regenerate, do not hand-edit. -->");
    println!(
        "\n**{total} aggregation methods across {} families.**\n",
        order.len()
    );
    for family in order {
        println!("## `{family}`\n");
        println!("| Method | Paper | Parameters read | Reproduced by |");
        println!("|---|---|---|---|");
        for e in &by_family[family] {
            let params = if e.params.is_empty() {
                "—".to_string()
            } else {
                e.params
                    .iter()
                    .map(|p| format!("`{p}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            };
            let reproduced = match baselines.get(e.name) {
                Some(names) => names
                    .iter()
                    .map(|n| format!("[`{n}`](../baselines/{n}/)"))
                    .collect::<Vec<_>>()
                    .join(", "),
                None => "—".to_string(),
            };
            println!(
                "| `{}` | {} | {} | {} |",
                e.name, e.citation, params, reproduced
            );
        }
        println!();
    }
}

fn print_json(
    by_family: &BTreeMap<&str, Vec<&conflux_config::StrategyEntry>>,
    order: &[&str],
    total: usize,
    baselines: &BTreeMap<String, Vec<String>>,
) {
    // Hand-written JSON, no serde dependency for a diagnostic example.
    // Strings here are all citations/names/params — no user input, no
    // control characters — so simple quote-escaping is sufficient.
    let esc = |s: &str| s.replace('\\', "\\\\").replace('"', "\\\"");
    println!("{{");
    println!("  \"total\": {total},");
    println!("  \"families\": [");
    for (fi, family) in order.iter().enumerate() {
        println!("    {{");
        println!("      \"name\": \"{family}\",");
        println!("      \"methods\": [");
        let methods = &by_family[family];
        for (mi, e) in methods.iter().enumerate() {
            let params = e
                .params
                .iter()
                .map(|p| format!("\"{}\"", esc(p)))
                .collect::<Vec<_>>()
                .join(", ");
            let reproduced = baselines
                .get(e.name)
                .map(|names| {
                    names
                        .iter()
                        .map(|n| format!("\"{}\"", esc(n)))
                        .collect::<Vec<_>>()
                        .join(", ")
                })
                .unwrap_or_default();
            let comma = if mi + 1 < methods.len() { "," } else { "" };
            println!(
                "        {{ \"name\": \"{}\", \"citation\": \"{}\", \"params\": [{params}], \"baselines\": [{reproduced}] }}{comma}",
                esc(e.name),
                esc(e.citation)
            );
        }
        let comma = if fi + 1 < order.len() { "," } else { "" };
        println!("      ]");
        println!("    }}{comma}");
    }
    println!("  ]");
    println!("}}");
}
