//! The committed catalog artifact must match the registry.
//!
//! `docs/AGGREGATION_CATALOG.generated.md` is generated by the `catalog`
//! example from the strategy registry. This test regenerates it and
//! diffs — so adding a method without regenerating, or hand-editing the
//! file, fails CI. That is the whole point of generating it: the catalog's facts
//! cannot silently drift from what the framework actually ships.

use std::process::Command;

#[test]
fn the_committed_catalog_matches_a_fresh_generation() {
    let committed = include_str!("../../../docs/AGGREGATION_CATALOG.generated.md");

    let output = Command::new(env!("CARGO"))
        .args(["run", "-q", "-p", "conflux-core", "--example", "catalog"])
        .output()
        .expect("run the catalog example");
    assert!(
        output.status.success(),
        "catalog example failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let fresh = String::from_utf8(output.stdout).expect("utf8 output");

    assert_eq!(
        committed.trim_end(),
        fresh.trim_end(),
        "docs/AGGREGATION_CATALOG.generated.md is stale — regenerate with \
         `cargo run -p conflux-core --example catalog > docs/AGGREGATION_CATALOG.generated.md`"
    );
}
