#!/usr/bin/env python3
"""Real-training test-harness client (docs/E2E_TESTING.md, Option A) —
extends stub_client.py's Register/FetchTask/SubmitDelta structure with
actual gradient descent on this client's own data shard, looped across
many rounds instead of stub_client.py's single shot.

Loads *only* its own shard file — never the full dataset — the same
discipline a real federated client has to follow.
"""

import argparse
import struct
import sys
import time
from pathlib import Path

import grpc
import numpy as np

# fl_transport_pb2*.py live in python/conflux_client/, generated by
# generate_proto.sh — this example's own directory doesn't duplicate them.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import fl_transport_pb2 as pb2
import fl_transport_pb2_grpc as pb2_grpc
from model import train_steps


def decode_weights(data: bytes) -> np.ndarray:
    count = len(data) // 4
    return np.array(struct.unpack(f"<{count}f", data), dtype=np.float32)


def encode_weights(weights: np.ndarray) -> bytes:
    return struct.pack(f"<{len(weights)}f", *weights.tolist())


def run(
    address: str,
    client_id: str,
    shard_path: str,
    rounds: int,
    lr: float,
    steps: int,
    poison: bool = False,
    poison_magnitude: float = 1000.0,
) -> None:
    shard = np.load(shard_path)
    X, y = shard["X"], shard["y"]
    print(f"[{client_id}] loaded {shard_path}: {len(X)} samples, class balance {y.mean():.2f}")
    if poison:
        print(f"[{client_id}] POISONED — every round submits offset weights instead of training")

    channel = grpc.insecure_channel(address)
    stub = pb2_grpc.FlTransportStub(channel)
    stub.Register(pb2.RegisterRequest(client_id=client_id, auth_token="harness-token"))
    print(f"[{client_id}] registered")

    last_round = None
    completed = 0
    while completed < rounds:
        # Poll until a *new* round is open — fetching the same round
        # twice would train on top of a submission we already made.
        while True:
            task = stub.FetchTask(pb2.FetchTaskRequest(client_id=client_id))
            if task.round != last_round:
                break
            time.sleep(0.2)

        weights = decode_weights(task.model_weights)
        if poison:
            # A persistent Byzantine client: every round, not stub_client.py's
            # single shot — this is what actually stresses a robust
            # aggregator across many rounds instead of just round 1.
            trained = weights + poison_magnitude
        else:
            trained = train_steps(weights, X, y, lr, steps)

        def chunks():
            yield pb2.DeltaChunk(
                client_id=client_id,
                round=task.round,
                chunk_index=0,
                total_chunks=1,
                data=encode_weights(trained),
                num_samples=len(y),
            )

        try:
            ack = stub.SubmitDelta(chunks())
        except grpc.RpcError as e:
            # A submission racing an already-closed round (Phase 10a) —
            # skip it and pick up the next round on the next loop
            # iteration, same as a real client would.
            print(f"[{client_id}] round {task.round} submission rejected ({e.code()}); retrying")
            last_round = task.round
            continue

        last_round = task.round
        completed += 1
        print(f"[{client_id}] round {task.round}: submitted, accepted={ack.accepted}")

    print(f"[{client_id}] done — completed {completed} rounds")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--address", default="127.0.0.1:47100")
    parser.add_argument("--client-id", required=True)
    parser.add_argument("--shard", required=True)
    parser.add_argument("--rounds", type=int, default=20)
    parser.add_argument("--lr", type=float, default=0.5)
    parser.add_argument("--steps", type=int, default=5)
    parser.add_argument(
        "--poison",
        action="store_true",
        help="submit offset weights every round instead of training — a persistent Byzantine client",
    )
    parser.add_argument("--poison-magnitude", type=float, default=1000.0)
    args = parser.parse_args()

    try:
        run(
            args.address,
            args.client_id,
            args.shard,
            args.rounds,
            args.lr,
            args.steps,
            args.poison,
            args.poison_magnitude,
        )
    except grpc.RpcError as e:
        print(f"[{args.client_id}] RPC failed: {e}", file=sys.stderr)
        sys.exit(1)
