[package]
name = "conflux-store"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"
tokio-postgres = "0.7"
tokio = { version = "1", features = ["rt"] }
tracing = "0.1"
aws-sdk-s3 = "1"
aws-config = "1"
aws-credential-types = "1"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
